/run/initialize

/gun/particle e-

/gun/energy 100 MeV
/run/beamOn 5000

/gun/energy 1 GeV
/run/beamOn 5000

/gun/energy 2 GeV
/run/beamOn 5000

/gun/energy 3 GeV
/run/beamOn 5000

/gun/energy 4 GeV  
/run/beamOn 5000

/gun/energy 5 GeV
/run/beamOn 5000

/gun/energy 6 GeV
/run/beamOn 5000

/gun/energy 7 GeV
/run/beamOn 5000

/gun/energy 8 GeV
/run/beamOn 5000

/gun/energy 9 GeV
/run/beamOn 5000

/gun/energy 10 GeV
/run/beamOn 5000
